global using OpenTK.Windowing.Common;
global using OpenTK.Windowing.Desktop;
global using OpenTK.Windowing.GraphicsLibraryFramework;
global using OpenTK.Mathematics;
global using Microsoft.Maui.Graphics.Skia;
global using OpenTK.Graphics.OpenGL;
global using SkiaSharp;
global using Microsoft.Maui.Graphics;
global using Caruti.Engine.Base;
